"""Build this port's resource DLL — Dolphin's own mechanism, on ARM64.

    python tools/build_resources.py              # generate .rc and build
    python tools/build_resources.py --rc-only    # just regenerate the .rc

WHY A DLL AND NOT A FOLDER OF FILES. Dolphin retrieves artwork by RESOURCE
IDENTIFIER, not by path:

    Image class >> fromId: anId
        ^self fromId: anId in: SessionManager.Current defaultResourceLibrary

    SessionManager >> defaultResLibPath      ^'DolphinDR8'

and `External.ResourceLibrary open:` locates that DLL relative to the working
directory, the image, then the install. Every icon reference in the corpus —
including the ones baked into view resources — is a string like
`'ClassBrowserShell.ico'` resolved through that library. Reproducing the
mechanism means the corpus's references work unaltered; replacing it with a
file-per-icon scheme would mean rewriting every reference and diverging from
Dolphin exactly where it is cheapest not to.

WHY OUR OWN, AND WHY IT KEEPS THE NAME. Object Arts' `DolphinDR8.dll` is
**32-bit x86**. Resources are architecture-neutral data and a 64-bit process
can read them with `LoadLibraryEx(..., LOAD_LIBRARY_AS_IMAGE_RESOURCE)`, but
`LoadImage` — the call `Image` actually makes — wants an ordinary module
handle, and loading a foreign-architecture DLL normally is not possible. So
this rebuilds the same resources into an ARM64 DLL. It keeps the name
`DolphinDR8.dll` deliberately: `defaultResLibPath` answers `'DolphinDR8'`, so
an identically-named library is the difference between zero code changes and
an override that would have to be maintained forever. Ours lives in this
repo's `resources/` and is never installed system-wide, so it cannot be
confused with an Object Arts installation.

The artwork is Dolphin's, MIT, Copyright (c) 2015 Object Arts — see
`resources/LICENSE.dolphin` and `resources/PROVENANCE.md`, which
`tools/extract_resources.py` writes and which must ship with the DLL.
"""
from __future__ import annotations

import argparse
import glob
import os
import subprocess
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
REPO = os.path.dirname(HERE)
RESDIR = os.path.join(REPO, "resources")
RC_PATH = os.path.join(RESDIR, "DolphinDR8.rc")
RES_PATH = os.path.join(RESDIR, "DolphinDR8.res")
DLL_PATH = os.path.join(RESDIR, "DolphinDR8.dll")

SDK_BIN = r"C:\Program Files (x86)\Windows Kits\10\bin"
MSVC = r"C:\Program Files\Microsoft Visual Studio\18\Professional\VC\Tools\MSVC"


def _find(root, name, must_contain):
    """Newest toolchain binary matching a path fragment."""
    hits = []
    for dp, _dn, fn in os.walk(root):
        if name in fn and all(m.lower() in dp.lower() for m in must_contain):
            hits.append(os.path.join(dp, name))
    return sorted(hits)[-1] if hits else None


def rc_name(name: str) -> str:
    """An RC resource name, written BARE — never quoted.

    rc.exe keeps the quotes as part of the name: a quoted `"HEADERPIN.BMP"`
    compiles to a resource literally called `"HEADERPIN.BMP"`, quotes and all,
    so every `FindResource` for `HEADERPIN.BMP` misses. The enumeration is
    what showed it — ours listed `'"HEADERPIN.BMP"'` where Object Arts' listed
    `'HEADERPIN.BMP'`.

    Dolphin's own `devres.rc` settles the form, and it is bare even for the
    awkward ones:

        !APPLICATION             ICON   "Res\\flipper.ico"
        ACCELERATORPRESENTER.ICO ICON   "Res\\AcceleratorPresenter.ico"

    `!` and `.` are both legal in an RC name; it is the QUOTES that are not
    wanted.
    """
    return name


def read_manifest():
    """(kind, resource name, relative path) as `extract_resources.py` recorded.

    NOT derived from the filenames. A resource name cannot be recovered from
    the file it was written to: `CLASSBROWSERSHELL.ICO` is a name INCLUDING
    the extension, while `!APPLICATION` is a name with none that had `.ico`
    appended to make a filename. Stripping the extension to guess got the
    first kind wrong and every `FindResource` for it missed with
    ERROR_RESOURCE_NAME_NOT_FOUND — with the resources plainly present in the
    DLL, which is a memorable way to lose an hour.
    """
    path = os.path.join(RESDIR, "MANIFEST.tsv")
    if not os.path.exists(path):
        raise SystemExit("no %s — run tools/extract_resources.py --write first"
                         % path)
    rows = []
    with open(path, encoding="utf-8") as fh:
        for line in fh:
            if line.startswith("#") or not line.strip():
                continue
            kind, name, rel = line.rstrip("\n").split("\t")
            rows.append((kind, name, rel))
    return rows


def generate_rc() -> int:
    lines = [
        "// GENERATED by tools/build_resources.py from MANIFEST.tsv.",
        "// Do not hand-edit.",
        "//",
        "// Dolphin Smalltalk's artwork, MIT, Copyright (c) 2015 Object Arts.",
        "// See LICENSE.dolphin and PROVENANCE.md in this directory.",
        "#pragma code_page(65001)",
        "",
    ]
    rows = read_manifest()
    for kind in ("ICON", "BITMAP", "CURSOR"):
        group = [r for r in rows if r[0] == kind]
        if not group:
            continue
        lines.append("// ---- %s (%d) ----" % (kind, len(group)))
        for _k, name, rel in group:
            lines.append('%-36s %-7s "%s"'
                         % (rc_name(name), kind, rel.replace("/", "\\\\")))
        lines.append("")
    with open(RC_PATH, "w", encoding="utf-8", newline="\r\n") as fh:
        fh.write("\n".join(lines))
    return len(rows)


def main(argv):
    ap = argparse.ArgumentParser()
    ap.add_argument("--arch", default="arm64", choices=("arm64", "x64"))
    ap.add_argument("--rc-only", action="store_true")
    args = ap.parse_args(argv)

    n = generate_rc()
    print("wrote %s (%d resources)" % (RC_PATH, n))
    if args.rc_only:
        return 0

    rc = _find(SDK_BIN, "rc.exe", [os.sep + args.arch])
    link = _find(MSVC, "link.exe", ["Hostarm64", os.sep + args.arch])
    if not rc or not link:
        print("toolchain not found (rc=%s link=%s)" % (rc, link), file=sys.stderr)
        return 2

    # rc.exe resolves the file paths inside the .rc relative to CWD, so it is
    # run FROM the resources directory rather than the repo root.
    r = subprocess.run([rc, "/nologo", "/fo", RES_PATH, RC_PATH],
                       cwd=RESDIR, capture_output=True, text=True)
    if r.returncode != 0:
        print("rc.exe failed:\n" + (r.stdout or "") + (r.stderr or ""),
              file=sys.stderr)
        return r.returncode
    print("compiled %s" % RES_PATH)

    # /NOENTRY: a resource-only DLL has no code and therefore no entry point.
    # Without it the linker demands one and fails with LNK2001 on _DllMainCRTStartup.
    r = subprocess.run([link, "/nologo", "/DLL", "/NOENTRY",
                        "/MACHINE:" + args.arch.upper(),
                        "/OUT:" + DLL_PATH, RES_PATH],
                       cwd=RESDIR, capture_output=True, text=True)
    if r.returncode != 0:
        print("link.exe failed:\n" + (r.stdout or "") + (r.stderr or ""),
              file=sys.stderr)
        return r.returncode
    print("linked %s (%d bytes, %s)"
          % (DLL_PATH, os.path.getsize(DLL_PATH), args.arch))
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
